version: '3'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always

  postgresql:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./database/init_scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    restart: always

  api:
    build: ./app
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: always
    depends_on:
      - postgresql

  # generator:
  #   build: ./service-generator
  #   ports:
  #     - "8080:8080"
  #   restart: always